In [16]:
import sys
sys.path.append("../")
import numpy as np

%load_ext autoreload
%autoreload 2

np.set_printoptions(threshold=5, precision=5)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
def print_heads(**kwargs):
    for k, v in kwargs.items():
        print(f"{k} = {v[:3]}")
    

In [38]:
from src.frontdoor_backdoor import generate_colangelo_ate
train, test = generate_colangelo_ate(100)

print("Train Data")
print_heads(backdoor=train.backdoor, treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structural = test.structural)

Train Data
backdoor = [[ 0.22354  0.05703  0.17019 ... -0.16663 -0.38089 -0.26082]
 [-0.39407  0.18578 -0.9105  ...  2.37692  1.66993 -0.00677]
 [ 0.52843  0.77897  0.75911 ... -0.90418 -0.4431   0.20819]]
treatment = [[ 0.74754]
 [ 0.71031]
 [-0.12221]]
outcome = [[ 0.83693]
 [-0.66913]
 [ 0.43152]]
Test Data
treatment = [[0. ]
 [0.1]
 [0.2]]
structural = [[0.  ]
 [0.13]
 [0.28]]


In [20]:
from src.frontdoor_backdoor import generate_acic_ate
train, test = generate_acic_ate()

print("Train Data")
print_heads(backdoor=train.backdoor, treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structural = test.structural)

Train Data
backdoor = [[-1.66202 -1.68405 -0.09911 ... -0.08919 -0.0896  -0.08919]
 [ 0.9707   1.04763 -0.09911 ... -0.08919 -0.0896  -0.08919]
 [ 0.38565 -0.59138 -0.09911 ... -0.08919 -0.0896  -0.08919]]
treatment = [[0]
 [0]
 [0]]
outcome = [[0.4035 ]
 [0.49904]
 [0.34912]]
Test Data
treatment = [[0]
 [1]]
structural = [[ 0.     ]
 [-0.55445]]


In [21]:
from src.frontdoor_backdoor import generate_ihdp_ate
train, test = generate_ihdp_ate()

print("Train Data")
print_heads(backdoor=train.backdoor, treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structural = test.structural)


Train Data
backdoor = [[-0.5286  -0.34345  1.12855 ...  0.       0.       0.     ]
 [-1.73694 -1.802    0.38383 ...  0.       0.       0.     ]
 [-0.80745 -0.20295 -0.3609  ...  0.       0.       0.     ]]
treatment = [[1.]
 [0.]
 [0.]]
outcome = [[ 3.78091]
 [-2.62334]
 [-1.62267]]
Test Data
treatment = [[0]
 [1]]
structural = [[-0.77517]
 [ 3.72409]]


In [23]:
from src.frontdoor_backdoor import generate_ate_dsprite_backdoor
train, test = generate_ate_dsprite_backdoor(n_data=100, rand_seed=42)

print("Train Data")
print_heads(backdoor=train.backdoor, treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structural = test.structural)

Train Data
backdoor = [[ 0.84275 -0.5389 ]
 [-0.13793 -0.46618]
 [ 0.0158   1.27658]]
treatment = [[ 0.07601  0.02292  0.05301 ... -0.03202  0.17595 -0.09035]
 [-0.07353 -0.09698  0.03235 ...  0.12283  0.05997 -0.07151]
 [ 0.0705  -0.22437 -0.07529 ... -0.03745  0.04162  0.00277]]
outcome = [[3.91007]
 [0.32579]
 [4.24666]]
Test Data
treatment = [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
structural = [[0.10298]
 [0.40033]
 [1.04702]]


In [27]:
from src.frontdoor_backdoor import generate_att_dsprite_frontdoor
train, test = generate_att_dsprite_frontdoor(n_data=100, rand_seed=42)

print("Train Data")
print_heads(frontdoor=train.frontdoor, treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment_cf=test.treatment_cf, treatment_ac=test.treatment_ac, target = test.target)

Train Data
frontdoor = [[14.72776]
 [22.98207]
 [ 6.64012]]
treatment = [[ 0.06433 -0.03946 -0.00051 ...  0.04138 -0.04419 -0.15739]
 [-0.08657  0.12813  0.00748 ...  0.03317  0.01845  0.15658]
 [ 0.04485  0.13278 -0.036   ... -0.10827  0.07801  0.03129]]
outcome = [[ 4.20926]
 [13.23138]
 [ 1.12358]]
Test Data
treatment_cf = [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
treatment_ac = [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
target = [[4.70475]
 [4.69068]
 [4.70146]]


In [28]:
from src.instrumental_variable import generate_demand_design_iv

train, test = generate_demand_design_iv(data_size=100, rho=0.5, rand_seed=42)

print("Train Data")
print_heads(instrumental=train.instrumental , treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structrual = test.structural)

Train Data
instrumental = [[ 1.06598  1.99908  1.     ]
 [ 0.15705  0.07362  6.     ]
 [-0.15863  7.86924  5.     ]]
treatment = [[14.36595]
 [17.445  ]
 [18.38008]]
outcome = [[  -9.7841 ]
 [-267.15419]
 [-248.83945]]
Test Data
treatment = [[10.]
 [10.]
 [10.]]
structrual = [[ 41.66667]
 [  3.33333]
 [-35.     ]]


In [29]:
from src.instrumental_variable import generate_demand_design_image_iv

train, test = generate_demand_design_image_iv(data_size=100, rho=0.5, rand_seed=42)

print("Train Data")
print_heads(instrumental=train.instrumental , treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structrual = test.structural)

1.7%

100.0%


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



100.0%

Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw




100.0%
100.0%


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

Train Data
instrumental = [[ 1.06598  1.99908  0.      ...  0.       0.       0.     ]
 [ 0.15705  0.07362  0.      ...  0.       0.       0.     ]
 [-0.15863  7.86924  0.      ...  0.       0.       0.     ]]
treatment = [[14.36595]
 [17.445  ]
 [18.38008]]
outcome = [[  -9.7841 ]
 [-267.15419]
 [-248.83945]]
Test Data
treatment = [[10.]
 [10.]
 [10.]]
structrual = [[ 41.66667]
 [  3.33333]
 [-35.     ]]


In [30]:
from src.instrumental_variable import generate_dsprite_iv

train, test = generate_dsprite_iv(data_size=100, rand_seed=42)

print("Train Data")
print_heads(instrumental=train.instrumental , treatment = train.treatment, outcome = train.outcome)

print("Test Data")
print_heads(treatment=test.treatment, structrual = test.structural)

Train Data
instrumental = [[0.7     2.2555  0.06452]
 [1.      5.31654 0.77419]
 [0.7     0.      0.64516]]
treatment = [[ 0.06433 -0.03946 -0.00051 ...  0.04138 -0.04419 -0.15739]
 [-0.08657  0.12813  0.00748 ...  0.03317  0.01845  0.15658]
 [ 0.04485  0.13278 -0.036   ... -0.10827  0.07801  0.03129]]
outcome = [[ 6.42653]
 [-2.17333]
 [ 6.15283]]
Test Data
treatment = [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
structrual = [[-4.11484]
 [-4.14043]
 [-4.23872]]


In [34]:
from src.proxy_causal import generate_deaner_experiment_pv

train, test = generate_deaner_experiment_pv("IM", 0)

print("Train Data")
print_heads(outcome=train.outcome, outcome_proxy=train.outcome_proxy, treatment_proxy=train.treatment_proxy,
           treatment=train.treatment)

print("Test Data")
print_heads(treatment=test.treatment, structrual = test.structural)

Train Data
outcome = [[4.70627]
 [4.82606]
 [4.81453]]
outcome_proxy = [[2.65765 3.08338 2.76897]
 [3.12341 3.4428  3.27097]
 [2.8677  3.20294 2.79457]]
treatment_proxy = [[4.13238 4.43279 3.40635 3.84175]
 [4.28773 4.54606 3.38325 3.87135]
 [4.02018 4.27992 3.34047 3.71051]]
treatment = [[0.09612]
 [0.07356]
 [0.04735]]
Test Data
treatment = [[-0.49  ]
 [-0.4599]
 [-0.4298]]
structrual = [[4.79221]
 [4.79221]
 [4.79221]]


In [35]:
from src.proxy_causal import generate_demand_pv

train, test = generate_demand_pv(100, 0)

print("Train Data")
print_heads(outcome=train.outcome, outcome_proxy=train.outcome_proxy, treatment_proxy=train.treatment_proxy,
           treatment=train.treatment)

print("Test Data")
print_heads(treatment=test.treatment, structrual = test.structural)

Train Data
outcome = [[30.98854]
 [36.48151]
 [40.8463 ]]
outcome_proxy = [[26.36979]
 [21.87639]
 [27.57243]]
treatment_proxy = [[-2.85763 -1.77662]
 [ 0.58304  0.33833]
 [ 1.0119   1.27055]]
treatment = [[31.57613]
 [24.10784]
 [27.69214]]
Test Data
treatment = [[10.     ]
 [12.22222]
 [14.44444]]
structrual = [[56.43016]
 [61.29142]
 [63.48692]]


In [37]:
from src.proxy_causal import generate_dsprite_pv

train, test = generate_dsprite_pv(100, 0)

print("Train Data")
print_heads(outcome=train.outcome, outcome_proxy=train.outcome_proxy, treatment_proxy=train.treatment_proxy,
           treatment=train.treatment)

print("Test Data")
print_heads(treatment=test.treatment, structrual = test.structural)

Train Data
outcome = [[-1.26951]
 [-1.60333]
 [-1.16874]]
outcome_proxy = [[-0.14685  0.00391  0.039   ...  0.04782 -0.15677 -0.05631]
 [ 0.00832 -0.03239 -0.08548 ... -0.03691  0.02167 -0.04946]
 [-0.0952  -0.02689  0.069   ... -0.01942  0.04945 -0.03168]]
treatment_proxy = [[0.6     0.64443 0.87097]
 [0.7     0.      0.64516]
 [0.6     0.64443 0.51613]]
treatment = [[-0.05857 -0.04726  0.05863 ...  0.00511 -0.13352  0.10918]
 [ 0.04071 -0.11348 -0.09135 ... -0.05225 -0.05065 -0.09085]
 [ 0.12819  0.04574 -0.12016 ... -0.01776  0.1686  -0.03412]]
Test Data
treatment = [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
structrual = [[-4.11484]
 [-4.14043]
 [-4.23872]]
